/root/ca/intermediate/certs/ca-chain.cert.pem: local-repo

local-repo:
	@echo cp -uv /root/ca/intermediate/certs/ca-chain.cert.pem
	sudo cp -uv /root/ca/intermediate/certs/ca-chain.cert.pem xe-ca-cert/etc/ssl/certs/xe-ca-chain.cert.pem
	sudo chown jakob:jakob xe-ca-cert/etc/ssl/certs/xe-ca-chain.cert.pem

