#!/bin/bash

set -e

FIRST_UID=1000
LAST_UID=29999
certificateFile="/etc/ssl/certs/xe-ca-chain.cert.pem"
certificateName="Xunde Energie Intermediate CA"


awk -F : '$3 >= fuid && $3 <= luid {print $6}' fuid=$FIRST_UID luid=$LAST_UID /etc/passwd | while read h; do
    echo h $h
    for certDB in $(find -H "${h}"/.mozilla* "${h}"/.thunderbird* "${h}"/.icedove* -name "cert8.db" 2>/dev/null)
    do
      echo certDB $certDB
      certDir=$(dirname ${certDB});
      #log "mozilla certificate" "install '${certificateName}' in ${certDir}"
      echo certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i ${certificateFile} -d ${certDir}
      certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i ${certificateFile} -d ${certDir}
    done
done
