#!/bin/bash

set -e

FIRST_UID=1000
LAST_UID=29999
certificateFile="/etc/ssl/certs/Xunde_Energie_Intermediate-CA-Chain.pem"
certificateNameDel="Xunde Energie Intermediate CA - Xunde Energie"
certificateName="Xunde Energie Intermediate CA"

echo Delete old CA Certificates

IFS=$'\n'
awk -F : 'BEGIN{OFS=" "} $3 >= fuid && $3 <= luid {print $1,$6}' fuid=$FIRST_UID luid=$LAST_UID /etc/passwd | while IFS=" " read -r u h; do
    for certDB in $(find -H "${h}"/.mozilla* "${h}"/.thunderbird* "${h}"/.icedove* -name "cert8.db" )
    do
      echo delete cert from $certDB
      certDir="$(dirname ${certDB})";
      r=0
      while test $r -eq 0 ;do 
          echo runuser -u $u -- certutil -d "${certDir}" -D -n "${certificateName}" ;
          runuser -u $u -- certutil -d "${certDir}" -D -n "${certificateName}" || r=$?
          echo return-value: $r
      done
    done
done

echo Install the new CA Certificate
IFS=$'\n'
awk -F : '$3 >= fuid && $3 <= luid {print $1,$6}' fuid=$FIRST_UID luid=$LAST_UID /etc/passwd | while IFS=" " read u h; do
    for certDB in $(find -H "${h}"/.mozilla* "${h}"/.thunderbird* "${h}"/.icedove* -name "cert8.db" 2>/dev/null)
    do
      echo $certDB
      certDir="$(dirname ${certDB})";
      echo runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "${certDir}" || echo error is $?
      runuser -u $u -- certutil -A -n "${certificateName}" -t "TCu,Cuw,Tuw" -i "${certificateFile}" -d "${certDir}" || echo error is $?
    done
done
